"""
Check the explanation, not just the result.

FINDINGS section 4 explains *why* the coefficient moves. That explanation makes
specific factual claims about this dataset, and an explanation that sounds right
is worth nothing if it was never measured. Each claim below is stated, measured,
and reported with a verdict, so a reader can see the reasoning is grounded rather
than plausible.

The claims:

  1. The predictors overlap. High balance use and being behind on payments tend
     to occur together, so the two share information and splitting credit between
     them depends on how much they overlap.
  2. The relationship is a cliff, not a slope. Default risk stays low and then
     jumps sharply once an account is a couple of periods behind.
  3. The copula flattens the cliff. A method that ties columns together with one
     number cannot represent a jump, so it comes out as a gentle slope.
  4. The rare-event pipeline steepens the cliff. Manufacturing extra rare cases
     fills the high-delay region with defaults at a higher rate than reality.

Run from the repo root:  python examples/certifier_demo/mechanism_check.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

import run_demo as demo

HERE = Path(__file__).resolve().parent
CLIFF_AT = 2          # periods behind, where the jump is claimed to happen


def default_rate_by_delay(frame: pd.DataFrame) -> pd.Series:
    """P(default | pay_delay_1 = k), for the k values with enough rows to trust."""
    d = frame[frame["pay_delay_1"].between(-2, 4)]
    g = d.groupby(d["pay_delay_1"].round().astype(int))["default"]
    return g.mean()[g.count() >= 30]


def main():
    real = pd.read_csv(demo.CSV)
    lines = ["<!-- Generated by examples/certifier_demo/mechanism_check.py. Do not edit. -->",
             "", "# Is the explanation true?", "",
             "Section 4 of FINDINGS explains why the coefficient moves. These are the",
             "factual claims that explanation rests on, each one measured.", ""]
    verdicts = []

    # ---- 1. do the predictors overlap? ----------------------------------
    r = float(real["utilization"].corr(real["pay_delay_1"]))
    ok = abs(r) >= 0.10
    verdicts.append(("Predictors overlap", ok))
    print(f"1. corr(utilization, pay_delay_1) = {r:+.3f}")
    lines += ["## 1. The predictors overlap", "",
              f"Correlation between how much of the limit is used and how far behind the "
              f"account is: **{r:+.3f}**.", "",
              f"{'Holds' if ok else 'DOES NOT HOLD'}: they do move together, so a "
              f"coefficient on one is not separable from the other." if ok else
              f"**Does not hold.** At {r:+.3f} these are close to unrelated, and the "
              f"overlap explanation is not supported.", ""]

    # ---- 2. is it a cliff or a slope? -----------------------------------
    rate = default_rate_by_delay(real)
    below = rate[rate.index < CLIFF_AT]
    above = rate[rate.index >= CLIFF_AT]
    jump = float(above.mean() - below.mean())
    steps = rate.diff().dropna()
    biggest_step_at = int(steps.idxmax())
    ok = jump > 0.20 and biggest_step_at == CLIFF_AT
    verdicts.append(("Cliff, not slope", ok))
    print(f"2. default rate by periods behind:\n{rate.round(3).to_string()}")
    print(f"   gap across the {CLIFF_AT}-period line = {jump:+.3f}; "
          f"biggest single step at {biggest_step_at}")
    lines += ["## 2. It is a cliff, not a slope", "",
              "Share of accounts that default, by how many periods behind they are:", "",
              "| periods behind | defaults |", "|---|---|"]
    lines += [f"| {k} | {v:.3f} |" for k, v in rate.items()]
    lines += ["",
              f"Average below the {CLIFF_AT}-period line is {below.mean():.3f} and above "
              f"it is {above.mean():.3f}, a gap of **{jump:+.3f}**. The largest single "
              f"step is at {biggest_step_at}.", "",
              ("Holds: risk is flat and then jumps, which is a shape a single "
               "correlation cannot describe." if ok else
               "**Does not hold** as stated; see the numbers above."), ""]

    # ---- 3 and 4. what the generators do to that shape ------------------
    lines += ["## 3 and 4. What each generator does to that shape", "",
              "The same measurement on each synthetic table.", "",
              "| source | corr with default | defaults below the line | above | gap |",
              "|---|---|---|---|---|"]
    print("3/4. per-source shape:")
    real_corr = float(real["pay_delay_1"].corr(real["default"]))
    real_row = (real_corr, float(below.mean()), float(above.mean()), jump)
    lines.append(f"| **real data** | {real_corr:+.3f} | {below.mean():.3f} | "
                 f"{above.mean():.3f} | {jump:+.3f} |")
    print(f"     {'real':<22} corr={real_corr:+.3f} gap={jump:+.3f}")

    made = {}
    for name, fn in (("gaussian_copula", demo.g_gaussian_copula),
                     ("REGEN", demo.g_regen)):
        syn = fn(real)
        c = float(syn["pay_delay_1"].corr(syn["default"]))
        rr = default_rate_by_delay(syn)
        b = rr[rr.index < CLIFF_AT].mean()
        a = rr[rr.index >= CLIFF_AT].mean()
        g = float(a - b)
        made[name] = (c, g)
        lines.append(f"| `{name}` | {c:+.3f} | {b:.3f} | {a:.3f} | {g:+.3f} |")
        print(f"     {name:<22} corr={c:+.3f} gap={g:+.3f}")

    flattens = made["gaussian_copula"][1] < jump and made["gaussian_copula"][0] < real_corr
    steepens = made["REGEN"][1] > jump or made["REGEN"][0] > real_corr
    verdicts.append(("Copula flattens the cliff", flattens))
    verdicts.append(("Rare-event pipeline steepens it", steepens))

    lines += ["",
              (f"The copula's gap is {made['gaussian_copula'][1]:+.3f} against a real "
               f"{jump:+.3f}, and its correlation with the outcome falls from "
               f"{real_corr:+.3f} to {made['gaussian_copula'][0]:+.3f}. "
               + ("It flattens the cliff, which is why its coefficient comes out too "
                  "small." if flattens else
                  "**This does not support the flattening explanation.**")),
              "",
              (f"The rare-event pipeline's gap is {made['REGEN'][1]:+.3f} and its "
               f"correlation is {made['REGEN'][0]:+.3f}. "
               + ("It steepens the cliff, which is why its coefficient comes out too "
                  "big." if steepens else
                  "**This does not support the steepening explanation.**")),
              "", "## Verdict", "",
              "| claim | measured |", "|---|---|"]
    for name, ok in verdicts:
        lines.append(f"| {name} | {'holds' if ok else '**does not hold**'} |")
    lines.append("")

    (HERE / "MECHANISM.md").write_text("\n".join(lines))
    print("\nVerdicts:")
    for name, ok in verdicts:
        print(f"   {'PASS' if ok else 'FAIL'}  {name}")
    print(f"\nTable → {(HERE / 'MECHANISM.md').name}")


if __name__ == "__main__":
    main()
